### ISSUE TITLE
Need to specify "reference" in terms of cigar operations in overlap

### ISSUE THREAD

**Issue by rlorigro** [GFA-spec/GFA-spec#100]
Since cigar operations are carried over from reference based alignment, it matters which sequence (left/right) in an overlap should be treated as the reference. With out this information, the meaning of an Insert or Delete is ambiguous. I can't find this specification in the documentation.

**Comment by ekg** [comment]
This should be clarified. I had to discover it when implementing gimbricate, and to be honest I've forgotten which way the relationship goes. This makes me worried that it might not be consistently implemented.

**Comment by rlorigro** [comment]
It turns out it is in the "Linkages" section of the GFA1 spec, but it's not in GFA2 as far as I can tell. Yes inconsistency would be difficult to recover from...

**Comment by sjackman** [comment]
If someone would like to copy the text from the GFA1 spec to the GFA2 spec and open a PR, I'd be happy to merge it.
