### ISSUE TITLE
Do two genes link together in GFA file indicate these two genes associate with each other?

### ISSUE THREAD

**Issue by limin321** [GFA-spec/GFA-spec#101]
Hi,

I ran PIRATE pangenome analysis of a group of bacteria strains, and one output file is called pangenome.gfa, which states unique connection between gene families.
In pangenome.gfa, I am able to see g005352 connects with all following gene families:
L	g004900	+	g005352	+	0M
L	g004979	+	g005352	+	0M
L	g005352	-	g006024	+	0M
L	g005352	-	g007263	+	0M
L	g005352	-	g014386	+	0M
**L	g005352	+	g004800	+	0M**
L	g015712	+	g005352	+	0M
L	g025775	+	g005352	+	0M
L	g026645	+	g005352	+	0M
L	g027770	+	g005352	+	0M
L	g034584	+	g005352	+	0M
L	g042506	+	g005352	+	0M

Because I am also interested in Gene association, so I ran coinfinder trying to see which genes are associated with each other. Interestingly, I also found the following two genes
**g005352**_000002__g005352,**g004800**_000002__g004800; are associated as indicated by PIRATE that they are uniquely connected.

My question is, how to understand the connections between genes in gfa files? Does it mean association among different genes?

I understand there will be overlapping when do genome assembly between different reads. However, my pirate input are either complete genomes or contigs, and the input for PIRATE is gff files from prokka annotation. How to understand these genes unique connections, and the overlapping between genes?  

Thank you so much.

Really appreciate that.
Best,
Limin

**Comment by sjackman** [comment]
You'd be better off asking this question to the maintainers of PIRATE at https://github.com/SionBayliss/PIRATE
