### ISSUE TITLE
Should a PG line (like in SAM) be codified in the spec?

### ISSUE THREAD

**Issue by SHuang-Broad** [GFA-spec/GFA-spec#103]
Hi,

I am reading the GFA2 spec and one thing about the alignment field of the edge records makes me thinking: 
should one want to "reproduce" the alignment (e.g. the CIGAR), a header line like that of `@PG` would be helpful, given that alignment is parameter-dependent in general.

Would that be useful, or too niche?

Thanks!

Steve

**Comment by SHuang-Broad** [comment]
ping to avoid being closed by the stale bot.

**Comment by sjackman** [comment]
Sounds fine to me. I'd suggest…
```
H PG:Z:…
```
If you want to be on the safe side, non-standard header lines should be lower case, until they're standardized.
```
H pg:Z:…
```
