### ISSUE TITLE
looking for a CLI tool to produce circular candidates from GFA

### ISSUE THREAD

**Issue by splaisan** [GFA-spec/GFA-spec#123]
Hi,

I am new to genome graphs, sorry of this is stupid.
I just did this manually in Bandage (GUI) and wondered if there is a tool or script that can output all fasta models from combinatorial circular closed paths in a gfa1 file (flye assembly). Can bandage CLI do this?

That would be handy for automation in my assembly pipeline which now ends with 4 contigs instead of a collection of 4 circular models.

thanks for your suggestions

my example data is as follows:

```
L	edge_1	+	edge_6	-	0M	RC:i:37
L	edge_1	-	edge_5	+	0M	RC:i:43
L	edge_2	+	edge_6	+	0M	RC:i:96
L	edge_2	-	edge_5	-	0M	RC:i:91
L	edge_3	+	edge_6	+	0M	RC:i:60
L	edge_3	-	edge_5	-	0M	RC:i:58
L	edge_4	-	edge_5	+	0M	RC:i:108
L	edge_4	+	edge_6	-	0M	RC:i:115
P	contig_5	edge_5+	*
P	contig_6	edge_6+	*
P	contig_1	edge_1+	*
P	contig_2	edge_2+	*
P	contig_3	edge_3+	*
P	contig_4	edge_4+	*
```
which has 4 circular solutions:

```
5+3+6+1
5+3+6+4
5+2+6+1
5+2+6+4
```

![Screenshot 2024-03-13 at 11 18 18](https://github.com/GFA-spec/GFA-spec/assets/858516/78b5ec71-9fd6-4ec0-ab77-1e3f8563dc81)

**Comment by ekg** [comment]
You'd want a combination of vg or odgi cover (sorry I have forgotten the subcommands) and odgi paths -f to get the FASTA. Then you can take unique paths.

**Comment by splaisan** [comment]
thanks, I have a look to both tools which I do not know yet and figure this out.
cheers
