### ISSUE TITLE
Comment Lines

### ISSUE THREAD

**Issue by noporpoise** [GFA-spec/GFA-spec#13]
I propose that lines beginning with `#` should be comment lines which are ignored. 

Comments would be useful when debugging, demonstrating examples and teaching.

They could also be used as a hacky solution to add user defined annotations into a file in the same way that javadoc / doxygen use source code comments.

**Comment by sjackman** [comment]
:+1: I'll merge a pull request if there are no dissenters.

> They could also be used as a hacky solution to add user defined annotations into a file in the same way that javadoc / doxygen use source code comments.

Although yes, I'd like to avoid this use of comments. I'd suggest that header `H` records with optional fields could be used for this purpose.

**Comment by noporpoise** [comment]
My understanding is that header lines can only appear at the top of a file. Is this true? Spec is unclear. 

My use case was that the user might want to bundle in some association between a set of Segments/Links after they have been declared. Example:

    # SNP r313131 seg100,link101,seg102/seg200,link201,seg202

This comment is skipped by general GFA tools, but the gives the user the opportunity to extend/abuse the file format without proposing an alteration to the format for their small use case.

**Comment by sjackman** [comment]
I propose a new JSON `J` record to contain completely arbitrary data.

| Column | Type | Description |
|---|---|---|
| 1 | Character | `J` |
| 2 | String | JSON |

**Comment by pb-jchin** [comment]
I do like to point out JSON is actually quite complicated format (although better than XML for its simplicity).   What we need is a restrict set of JSON? A simple example, do we allow `\n` in the JSON string? If we do, the parse need to know that.

**Comment by sjackman** [comment]
Yes, I agree, Jason. In particular, the characters `\t` and `\n` must not appear in the JSON.

**Comment by noporpoise** [comment]
Yes @pb-jchin, parsers need to be aware of new lines within JSON objects. I've written similar code \[1\] that reads until the end of a JSON object (for loading JSON headers) -- it's about 40 lines of code in C. 

Using JSON does mean that lines starting with S might not be segment lines. This may upset some people who rely on `awk`. It wouldn't be hard to write a GFA tool that stripped JSON annotations though. 

I don't think we need to restrict to a subset of JSON. Other people may prefer that we do not allow any new line characters in strings or in JSON objects. I can understand the motivation. 

\[1\]: https://github.com/mcveanlab/mccortex/blob/9adb394ce978c2cbd7f718da6e08beae5ea54dbc/src/graph/json_hdr.c#L13

**Comment by sjackman** [comment]
Let's move this discussion regarding the JSON format to #15.

**Comment by sjackman** [comment]
@noporpoise Would you open a pull request proposing that lines starting with `#` are comments?
