### ISSUE TITLE
Start/end positions in paths

### ISSUE THREAD

**Issue by rrwick** [GFA-spec/GFA-spec#24]
Should GFA paths include a way to specify the start and end positions?  Perhaps through the use of optional tags?  I'm thinking something like `ST` to give the start position in the first segment and `EN` to give the end position in the last segment.

For example:

```
H   VN:Z:1.0
S   1   AGCGTA
S   2   TAACAG
L   1   +   2   +   0M
P   A   1+,2+   0M
P   B   1+,2+   0M  ST:i:4  EN:i:3
P   C   1+      ST:i:5
P   D   2+      ST:i:2  EN:i:5
```

In this case, path A's sequence is `AGCGTATAACAG`, which is the entirety of segment 1 followed by the entirety of segment 2.  Path B's sequence is `GTATAA`, starting at position 4 in segment 1 and ending at position 3 in segment 2.

This would also allow for specifying parts of a single segment.  Path C's sequence is `TA` and path D's sequence is `AACA`.

In those examples I went with 1-based indexing with an inclusive end position.  This is in contrast to something like Python which uses 0-based indexing and exclusive range ends.  Do people agree with 1-based inclusive ranges?

And it's a bit weird that the paths with only one segment are lacking any CIGAR strings.  Since the CIGAR list field is required, I put two tabs between the segment list and the tags.

Thoughts?

**Comment by sjackman** [comment]
The containment record uses 0-based coordinates. With 0-based, I think the coordinates should be open ended, that my preference anyway. In any case, it should be consistent thoughout the spec.

If the CIGAR field is empty, use an asterisk *.

Perhaps the clipping operation of the CIGAR field could be used to represent start and end coordinates? I haven't really thought this through. Sorry, just barfing up thoughts right now.

**Comment by jmarshall** [comment]
Strong :+1: to 0-based exclusive-end (i.e., half-open) for a low-level machine-orientated format like this.  See also the GA4GH discussion at ga4gh/schemas#121.
