### ISSUE TITLE
Strict ordering in GFA (?)

### ISSUE THREAD

**Issue by edawson** [GFA-spec/GFA-spec#25]
I've been working on [a C++ parser for GFA](https://github.com/edawson/gfakluge) to replace the old parser in vg with and was wondering whether there's an expected order for S/L/P/C/(x/a) lines in GFA. 

Currently I print things so that the source sequence of a link or containment always appears immediately before links/containments coming from that source. Sequences are sorted alphanumerically by their name. I've run in to a few GFA files that don't follow either convention though, and to be honest these orderings are mostly just so that my output matches the output of the previous parser in vg.

I understand that the lines are independent and we could place the P/L/C lines for a given S line anywhere in the file, but if there's a different convention I'd like to go ahead and follow it.

**Comment by pmelsted** [comment]
There is no fixed ordering so a parser will have to accept any possible order. 

The only exception would perhaps be the header line, it would be sort of rude to not have it be the first line, but that's not in the spec yet.

**Comment by edawson** [comment]
I guess I was more concerned about output, so that's fine then. It would indeed be a bit coarse to put a header line anywhere but the header.

Thanks!

**Comment by sjackman** [comment]
ABySS requires that the segments be output before any links that refer to those segments. I'd like to see that be a requirement of the spec. My preference is that the records are grouped together by type in the order `H`, `S`, `L` then `P`. I haven't thought about the other record types. It would have been nice if the record types were in alphabetical order. Oh well.

**Comment by pmelsted** [comment]
I think it makes sense to not allow links to refer to paths that haven't been defined yet, similarly for paths. A stronger version of this is to specify everything in a strict order, H, S, L P.

It makes the parsing less painful and shouldn't be a burden on producing the output.

**Comment by ekg** [comment]
But to enforce it in the schema seems overly heavy handed. In any case we
can fix the ordering via a sort. I would suggest we leave it unspecified
what the order might be.

**Comment by sjackman** [comment]
I propose that

1. The definition of segments should precede the definition of the links that are incident to those segments.
2. The definition of segments and links should precede the definition of paths that reference those segments and links.

Any dissenters?

**Comment by ekg** [comment]
I dissent. I think we should not impose an ordering I'm the spec. It will
only cause pain and has no effect on the semantic content of what is
transmitted.

**Comment by sjackman** [comment]
Okay. How about adding it to the spec as a *should* rather than *must*, as a recommendation rather than a requirement? (as per https://www.ietf.org/rfc/rfc2119.txt)

**Comment by sjackman** [comment]
Even when it doesn't affect the semantic content, I think making the format as easy to parse as possible for implementers is an important consideration.

**Comment by edawson** [comment]
I think it's certainly more convenient to parse things if we ensure that one segment of a link is given before the link (e.g. a link's source is always given before that link). But I'm not sure I like requiring both ends to be defined beforehand. This does get complicated with inversions as well. This advantage goes away if we parse things to a map beforehand anyway.

I'm strongly opposed to the HSLP ordering. While it contains all the elements and is easy to parse by machines, to me it's harder for a human being to parse. It destroys the "graphiness" of GFA by decomposing the graph into loose sets of elements. It's nice to find a segment in the file and immediately see if it's highly connected based on how many link lines follow its definition and whether it is on any paths.

**Comment by edawson** [comment]
Also sorting on the source nodes of elements (S, C, L, P lines) is nice - it's easy enough to enforce alphanumeric sorting and it might simplify random access.

**Comment by sjackman** [comment]
SAM allows specifying in the header whether the file is ordered or not. That makes sense here too.

**Comment by edawson** [comment]
Good point - if there's an equivalent to `samtools sort` for gfa (and a well-defined sorting order) for GFA it seems reasonable to allow both.

**Comment by sjackman** [comment]
There is no `gfatools sort` yet, but I think we'll need one for certain.

**Comment by edawson** [comment]
I'm on it - I'll push something [here](https://github.com/edawson/gfakluge.git) today. Unfortunately my javascript is too rusty to push it to gfatools proper.

**Comment by sjackman** [comment]
I regularly sort SAM files with the UNIX sort utility. It would be nice if GFA could be sorted with the UNIX sort utility. It's unfortunate that there's not a clear way to specify the sort order of the record types to UNIX sort.

**Comment by sjackman** [comment]
You could do a hacky thing where you change `H` to `0`, `S` to `1`, `L` to `2`, et c, then sort, then convert back, but that hackery kind of defeats the benefit of using an off the shelf tool.

**Comment by ekg** [comment]
I have typically sorted on the second column with sort -k2. This yields an
output in which local regions of the graph tend to occur together.
Although, I tend to use numerical IDs, which probably changes things.

**Comment by sjackman** [comment]
I also tend to use numerical IDs, but for simplicity I think the specified ordering should be ASCII ordered. You can always pad with `0`s at the left to get consistent numerical ordering.

**Comment by edawson** [comment]
There's now a [gfa_sort](https://github.com/edawson/gfakluge/blob/master/gfa_sort.cpp) utility in gfakluge.

Alphanumeric sort on seg IDs, non-blocked:  
`./gfa_sort -i reads.gfa` or `./gfa_sort --gfa-file reads.gfa`

Blocked (`HSLC`) format and alphanumeric sort in each block:
`./gfa_sort -i reads.gfa -b` or `./gfa_sort --gfa-file reads.gfa --block-order`

**Comment by lh3** [comment]
I also prefer NOT to impose ordering, except the header line. Having `S` lines above `L` lines does make programming easier, but not having this requirement is not too bad.

**Comment by ggonnella** [comment]
A general strict ordering may not be necessary, but I think we still should mandate the header to be on the top. I opened for this reason I different issue on that.

**Comment by edawson** [comment]
It should be possible to `sort` GFA without knowing the spec version; then the header lines should float to the top, and it should be easy to determine the `VN` from there. That being said, I agree with the idea posed in #39 that it is nice to have the `H    VN` as the first line in the file.

**Comment by ggonnella** [comment]
Yes, of course it is still possible to basically look for the VN in the file before really parsing it, but I think this should not be required. For the current files, I can parse the file in one pass (by introducing some "virtual" lines, such as S which I expect but did not came up yet), but if I have to look for the VN first, this will not be possible anymore.
