### ISSUE TITLE
GFA version 2 with branches, external ids, and non-mandatory CIGAR

### ISSUE THREAD

**Issue by richarddurbin** [GFA-spec/GFA-spec#31]
Hello all,

I am at Schloss Dagstuhl with Gene Myers, Jason Chin, Adam Phillipy and others.  We would like to propose a major revision to GFA that addresses a number of issues raised in particular by long reads with high error rates from PacBio and ONT, on the basis that Gene and Jason and others would adopt the result for their pipelines.

The key issues addressed are:
  1) move CIGAR strings from required fields to CG:Z:<string> optional fields, replacing them by required lengths in the two segments in the Link lines and equivalents elsewhere.  CIGAR is not optimal or necessary for long single molecule technology reads.
  2) require a length for Segment fields, before the (optional) string for the sequence
  3) introduce a new optional Piece record, that says how Segments are made from Pieces with external ids.  e.g. how reads align to a unitig, or how unitigs align to later longer contigs/scaffolds.  This sorts traceability through an assembly process.
  4) support branches where a Segment end inserts into the middle of another Segment.  This supports alternates of bubbles, so allowing long primary called contigs with variants.  As in ALTs on the human reference, or the results of bubble detection and primary sequence choice to achieve long contiguous primary assembly contigs.  We do this by extending the C (Contain) syntax.

Also a number of other standard tags are proposed, both in the header and elsewhere, to facilitate parsing (e.g. number of records of each type specified in the header to enable preallocation) and support for alternate representation of alignments (trace points - see Gene's Dazzler blog).

Are github issues the right way to discuss these proposals?  I don't know who monitors this site?
Gene has a document that we have jointly worked on, which will be ready for posting tomorrow I think.  I could also create a pull request on the current spec, but am not sure that is the right way to go. 

Richard

**Comment by sjackman** [comment]
> 1) move CIGAR strings from required fields to CG:Z: optional fields, replacing them by required lengths in the two segments in the Link lines and equivalents elsewhere. CIGAR is not optimal or necessary for long single molecule technology reads.

CIGAR strings are optional, and I agree are not the best representation for read-read overlaps. Replac the cigar string with an asterisk `*`. Suggested change to the spec: Change `CIGAR string describing overlap` to `optional CIGAR string describing overlap`.

**Comment by sjackman** [comment]
> 2) require a length for Segment fields, before the (optional) string for the sequence

Parsing dynamic fields is not onerous, as argued by Heng Li in private communication. The sequence column is optional. Replace it with an asterisk `*` as desired. Suggested changed to the spec: Change `The nucleotide sequence` to `optional nucleotide sequence`.
https://github.com/pmelsted/GFA-spec/blob/master/GFA-spec.md#required-fields

**Comment by sjackman** [comment]
> 3) introduce a new optional Piece record, that says how Segments are made from Pieces with external ids. e.g. how reads align to a unitig, or how unitigs align to later longer contigs/scaffolds. This sorts traceability through an assembly process.

I would prefer to use the widely accepted SAM/BAM to indicate the alignment of reads to unitigs, contigs to scaffolds, et c. My preference is a separate SAM/BAM file, but if the motivation is to include all the relevant information in a single file, we can discuss how to encapsulate a SAM file in a GFA file with a SAM record type, which wouldn't be at all difficult.

**Comment by sjackman** [comment]
> 4) support branches where a Segment end inserts into the middle of another Segment. This supports alternates of bubbles, so allowing long primary called contigs with variants. As in ALTs on the human reference, or the results of bubble detection and primary sequence choice to achieve long contiguous primary assembly contigs. We do this by extending the C (Contain) syntax.

When the bubble is a closed bubble as defined in Heng's Fermi paper [doi:10.1093/bioinformatics/bts280](http://bioinformatics.oxfordjournals.org/content/28/14/1838.short) I would like to see a self-contained subgraph also described by GFA within the containing GFA file. This issue becomes trickier I think when the bubble is not self-contained, that is, when there are links between subgraphs.

**Comment by sjackman** [comment]
@aphillippy @cschin @jts @lh3 @pb-chin @pmelsted @richarddurbin @rrwick @thegenemyers

**Comment by rrwick** [comment]
@sjackman's idea for Bandage sounds very cool, but I cringe at the thought of implementing it! :)

Regarding number 4, Shaun's comments and the general topic of encoding variants in GFA, I'd be curious to hear people's thoughts on the other approach: encoding all variation _explicitly_ with segments and links. For example, this hypothetical graph has a bubble in the first segment and another segment which joins in the middle (as discussed above in item 4).
```
S	1	C[TG]GGATGT
S	2	AGCA
# Some line here indicating that segment 2 joins into the middle of segment 1.
```
Whereas this describes the same arrangement using only segments and links:
```
S	1	C
S	2	T
S	3	G
S	4	GG
S	5	ATGT
S	6	AGCA
L	1	+	2	+
L	1	+	3	+
L	2	+	4	+
L	3	+	4	+
L	4	+	5	+
L	6	+	5	+
```
The second one is definitely more verbose, but (IMHO) conceptually simpler. It does, however, break up long contigs wherever variation occurs. Richard said (in email), 'This is one of the barriers to people adopting GFA, because many assemblers want to present long primary contigs', and I sympathise with that view.

So if the GFA format was to go with the segment-and-link-only approach, then I think people need to be encouraged to use path lines to describe long contigs. Perhaps we could also allow sequences in path lines. This would be somewhat redundant, but it would allow long contigs to be presented in their entirety:
```
P	1	1+,2+,4+,5+	CTGGATGT
```
My task with Bandage is then to visualise graph paths in a useful manner. That has actually long been on my to-do list and it will (I promise!) happen someday :)

Thoughts on this? My personal preference is for the segment-and-link-only approach, though I'm willing to be swayed. What use-cases do people have that would be awkward with only segments, links and paths?

**Comment by rrwick** [comment]
And as a side note, I'm happy to see GFA getting more attention lately and want to see it become useful to as many people as possible. A couple times I've talked to somebody working with sequence graphs (in their own custom format) and I tell them, 'Use GFA!'

**Comment by rrwick** [comment]
One other, unrelated request if we're considering a new GFA version: an optional depth tag for segments. The current RC and KC tags count reads and k-mers, but that's not quite the same thing as read _depth_ or k-mer _depth_. In an Illumina set, the reads may all mostly have the same length, in which case read count and read depth would correlate tightly. But for long reads where there is a lot more variation in length, that's not true. As Richard said at the start, GFA should be updated to work well with long reads, and I think a depth tag (something like `DP:f`) would be a nice option to have.

**Comment by pb-jchin** [comment]
Here are some thought about "piece" and "path". Basically, in my experience, I find that it is useful to have a way to store a set of "links".  For example, I will like to be able to do some queries like "give me all links that are 'associated' with a contig". The set of "links" associated with a contig may be more the a path. For example, some spurs or bubbles removed during graph-to-contig layout may be throw away but they will be useful for diploid assembly or give assessment of remaining ambiguities related to the contig. It will be useful we have some way to store such subsets, although I think we can discuss whether we need to storage the information of such sets in the same GFA file.

**Comment by thegenemyers** [comment]
Hi all.  I think the horse is out of the barn a bit early.  I'm putting the finishing touches on the proposal and maybe it would be a good idea for all to see the proposal rather than Richard's preliminary list of features which was only intended to tell you what we were up to.  I've been reading the discussion and have already made some adjustments to the doc I am working with based on what I've read.  I'll try to turn my word doc into a suitable .md doc and put it in a repository that we can then work versions on.  Sound OK?

**Comment by pmelsted** [comment]
I agree that it would be good to see the big picture roadmap, although Richard's feature list hinted at that, before splitting it up into discrete tasks.

Also a google doc can be easier to view/share/modify than in a repo.

**Comment by richarddurbin** [comment]
There was an open discussion about this all in the Assembly discussion group here at Dagstuhl this morning.  As can be expected, there is tension between conservative approaches keeping as consistent as possible with GFA version 1, and more radical approaches that change more.

Some comments are:
    - the XY:<type>:<value> syntax is a mistake in the text format (fine in binary).  Instead we should infer the type from the string for the value as mordern programming languages, such as requiring a decimal point for float, double quotes for a text string, single quotes for a char, 0x prefix for hex, some other prefix for Jason etc.  Without this you risk (and get) inconsistency. [Pascal Costanza - Intel].  Personally I feel that this does not really solve inconsistencies - you can still open a double quote and not close it, etc.

         - related to this, in trying to implement a C parser I myself have a problem with array type B.  How do I know whether the elements are ints or floats?  Can there be different symbols for these?

  - how to represent phased haplotypes?  It was suggested that these can be segments, in which case we would like to indicate where they align.

 - this moved to a discussion to extend the Contain/Branch join record even further, to allow an arbitrary local alignment of a subsegment of s1 to a subsegment of s2.  That could also subsume Link.  There was to and fro argument about whether to keep Link special-cased.

 - subsequently Gene proposed to add a scaffolding record, i.e. a pair of segments with orientations and some gap size estimate.  This should be different from a Link, even a zero gap end-butting link (which should be a Link).

**Comment by thegenemyers** [comment]
I will get the doc up as soon as possible.  While google doc seems reasonable it won't allow
version control.  I think the way to go is to create a fork and then deposit the proposal as an .md file in the fork.  Please give me a chance to put the doc up so y'all can really see what the proposal is.

**Comment by ekg** [comment]
> 3) introduce a new optional Piece record, that says how Segments are made from Pieces with external ids. e.g. how reads align to a unitig, or how unitigs align to later longer contigs/scaffolds. This sorts traceability through an assembly process.

What is the typical way of storing alignments in GFA? I'm thinking of both sequences embedded in the graph (pieces/parts/paths) and external sets of alignments that describe differences from the graph (akin to BAM). Could these be represented the same way?

**Comment by thegenemyers** [comment]
OK, I've created a fork and you can find a first version of the GFA2 proposal here:

https://github.com/thegenemyers/GFA-spec

The new spec is GFA2-spec.md.

Please read it before commenting further.  Perhaps we could also start another issue thread in direct response to the document at my fork?

   Cheers,  Gene

**Comment by sjackman** [comment]
> - the XY:: syntax is a mistake in the text format (fine in binary). Instead we should infer the type from the string for the value as mordern programming languages, such as requiring a decimal point for float, double quotes for a text string, single quotes for a char, 0x prefix for hex, some other prefix for Jason etc. Without this you risk (and get) inconsistency. [Pascal Costanza - Intel]. Personally I feel that this does not really solve inconsistencies - you can still open a double quote and not close it, etc.

I proposed exactly this concept for the type system, and the proposal was voted down. I'm reasonably happy with either system. It's a good example though of why each proposal needs its own issue so that we can easily refer back to previous proposals that have been proposed, voted, and decided. The audience of GFA is clearly larger now, so it is reasonable to revisit decided issues, but there needs to be an overwhelming argument to reopen decided issues.

**Comment by sjackman** [comment]
> related to this, in trying to implement a C parser I myself have a problem with array type B.  How do I know whether the elements are ints or floats?  Can there be different symbols for these?

The array type `B` is an array of bytes, that is `uint8_t`, an unsigned 8-bit integer.

**Comment by sjackman** [comment]
@rrwick wrote…
> One other, unrelated request if we're considering a new GFA version: an optional depth tag for segments. The current RC and KC tags count reads and k-mers, but that's not quite the same thing as read depth or k-mer depth.

I propose adding `NC` for nucleotide count, meaning the number of nucleotides that align to this segment. Dividing `NC` by the number of nucleotides in the segment gives the depth of coverage.

**Comment by sjackman** [comment]
> subsequently Gene proposed to add a scaffolding record, i.e. a pair of segments with orientations and some gap size estimate. This should be different from a Link, even a zero gap end-butting link (which should be a Link).

:+1: I proposed adding distance estimates to the link `L` record in #9

**Comment by sjackman** [comment]
@rrwick wrote…
> So if the GFA format was to go with the segment-and-link-only approach, then I think people need to be encouraged to use path lines to describe long contigs.

:+1: If needed, containment records `C` could show how the atomic segments `S` align to the path segment `P`.

**Comment by sjackman** [comment]
> OK, I've created a fork and you can find a first version of the GFA2 proposal here:
https://github.com/thegenemyers/GFA-spec

@thegenemyers Hi, Gene. Could you please open a pull request? That'll create a new issue on this repository where we can discuss your proposal.

**Comment by richarddurbin** [comment]
Ok. Makes sense. But that is not what the GFA spec says. It says "integer or numeric array" and allows decimal points in its regexp. What is the correct code for an array of ints?  Maybe I should look at the SAM or VCF spec. 

Richard

Sent from my iPhone

> On 31 Aug 2016, at 8:02 pm, Shaun Jackman <notifications@github.com> wrote:
> 
> related to this, in trying to implement a C parser I myself have a problem with array type B. How do I know whether the elements are ints or floats? Can there be different symbols for these?
> 
> The array type B is an array of bytes, that is uint8_t, an unsigned 8-bit integer.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by richarddurbin** [comment]
I agree there is not enough case to change this. I was just reporting that it was raised. 

Sent from my iPhone

> On 31 Aug 2016, at 8:00 pm, Shaun Jackman <notifications@github.com> wrote:
> 
> the XY:: syntax is a mistake in the text format (fine in binary). Instead we should infer the type from the string for the value as mordern programming languages, such as requiring a decimal point for float, double quotes for a text string, single quotes for a char, 0x prefix for hex, some other prefix for Jason etc. Without this you risk (and get) inconsistency. [Pascal Costanza - Intel]. Personally I feel that this does not really solve inconsistencies - you can still open a double quote and not close it, etc.
> I proposed exactly this concept for the type system, and the proposal was voted down. I'm reasonably happy with either system. It's a good example though of why each proposal needs its own issue so that we can easily refer back to previous proposals that have been proposed, voted, and decided. The audience of GFA is clearly larger now, so it is reasonable to revisit decided issues, but there needs to be an overwhelming argument to reopen decided issues.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by sjackman** [comment]
No worries at all. Please do!

**Comment by sjackman** [comment]
I've clarified that segment sequence and link CIGAR are optional in e70a22d10ea9efedcf07caf803f17689386f2e8f

**Comment by richarddurbin** [comment]
I think that if people are going to report the long contigs as contigs then they had better be represented as contigs in the final GFA file, that is in Segment records. 

Richard

Sent from my iPhone

> On 31 Aug 2016, at 8:18 pm, Shaun Jackman <notifications@github.com> wrote:
> 
> @rrwick wrote…
> 
> So if the GFA format was to go with the segment-and-link-only approach, then I think people need to be encouraged to use path lines to describe long contigs.
> 
> 👍 If needed, containment records C could show how the atomic segments S align to the path segment P.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by sjackman** [comment]
I think a Path `P` record could have an accompanying segment `S` record giving its sequence for this use case.

Incidentally, it's possible to create a FASTA index (.fai) file of a GFA file (the GFA file itself, not an accompanying FASTA file) such that `samtools faidx` (and I presume other tools) can extract sequences from the GFA file! Maybe just a parlour trick, but I think that's pretty cool.

**Comment by sjackman** [comment]
After rereading my earlier responses, some seemed terse verging on rude. Sorry if I put anyone off! It wasn't my intent. I'm very excited to see such interest in GFA.

I'll be out of town at a friend's wedding from Friday until Tuesday. I look forward to catching up on the discussion when I get back.

**Comment by sjackman** [comment]
Ping Giorgio Gonnella @ggonnella of `Ruby library for handling GFA files` https://github.com/ggonnella/rgfa
