### ISSUE TITLE
Discussion for storing subsets of links in GFA

### ISSUE THREAD

**Issue by pb-jchin** [GFA-spec/GFA-spec#32]
Here are some thought about "piece" and "path". Basically, in my experience, I find that it is useful to have a way to store a set of "links". For example, I will like to be able to do some queries like "give me all links that are 'associated' with a contig". The set of "links" associated with a contig may be more the a path. For example, some spurs or bubbles removed during graph-to-contig layout may be throw away but they will be useful for diploid assembly or give assessment of remaining ambiguities related to the contig. It will be useful we have some way to store such subsets, although I think we can discuss whether we need to store the information of such sets in the same GFA file.

To track the discussion related to this issue. I will open a new issue.

**Comment by sjackman** [comment]
Hi, Jason. Can you please give a concrete example of your proposal? What record types or attributes do you propose adding to the GFA spec?

**Comment by pb-jchin** [comment]
The GFA1/2 as stand can store arbitrary overlaps. When one can probably specific a path, but a path is just a special subgraph ( a very useful one without doubt). However, there will be cases that certain set of overlaps which may not be a path that is important to catch. For example, "bubbles" may not be two paths. There is typically cross-branch edges inside a bubble. The subgraph that is related to a contig may not be a simple path in diploid assembly case. I will like to catch those.

**Comment by sjackman** [comment]
Okay, I believe I understand now. You would like to specify a set of segments that compose a subgraph, like for example a bubble. Is it a set of segments, or a set of links, or a set of each?

**Comment by pb-jchin** [comment]
set of links. Note that in the current proposal in either GFA1/2, it can included all overlaps. Many overlaps will be removed during the transitive reduction stage. The final assembly graph only uses a subset of overlaps/links.

**Comment by sjackman** [comment]
Perhaps add a subgraph identifier to the optional attributes (tags) of the link `L` record.

**Comment by pb-jchin** [comment]
yes. that is an possibility to encode subset.

**Comment by sjackman** [comment]
If that meets your use case, feel free to propose an optional `SG` (subgraph) tag for both segment `S` and link `L` records.

**Comment by pb-jchin** [comment]
one question remains is what is the minimum information for uniquely identifying a `L` record. Note that it is possible two reads can overlapped in legitimately different ways, e.g. if a read has inverse repeats from one of its end to the other.

**Comment by sjackman** [comment]
Right now there is no way to uniquely identify a link. That is needed for the subgraph `SG` proposal. If you have a use case for uniquely identifying links, I would endorse a proposal to add an `ID` attribute that assigns a unique integer to a link `L` record.

**Comment by sjackman** [comment]
What should the type of the subgraph `SG` tag be, integer or string?
