### ISSUE TITLE
Has any implementation of GFA implemented the containment C record?

### ISSUE THREAD

**Issue by sjackman** [GFA-spec/GFA-spec#34]
See https://github.com/pmelsted/GFA-spec/issues/33#issuecomment-243905116

**Comment by ilyaminkin** [comment]
A kind of: https://github.com/medvedevgroup/TwoPaCo

The code is not "released" yet, though.

**Comment by sjackman** [comment]
Okay. Good to know. Perhaps the `C` record should be left as is then. If no one had implemented it, I was thinking we could possibly get rid of it. Would you like to comment on #33?

**Comment by ilyaminkin** [comment]
I will take a look.

**Comment by ggonnella** [comment]
I notice that, in commit c881263, recently merged in the specification, there is a description of C lines, which I find confusing on one point.

I.e. until now I thought that the C (as well as L) "from" and "to" fields were supposed to be segment names from S lines in the graph. In the note about "pan-genome" motivation for C, it sounds like one can have a C between a S and a chromosome sequence which is external, not contained in the graph.

I think it would be better to clarify this in the specification text.

**Comment by ilyaminkin** [comment]
@ggonella you are right. The point is to keep the mapping between pan-genome graph and input sequences, see https://github.com/GFA-spec/GFA-spec/issues/7 .

**Comment by sjackman** [comment]
I agree with Giorgio @ggonnella that the containment `C` record is between two segment `S` records both in the GFA file. GFA doesn't currently have any concept of external IDs. I suggest changing the text like so:


```
 # `C` Containment line
 
-This line can be used to describe mapping between segments in the graph and input sequences. It is useful for graphs built from assembled genomes, e.g. pan-genome analysis graphs.
+A containment line represents an overlap between two segments where one is contained in the other.
```

**Comment by sjackman** [comment]
@ggonnella @ilyaminkin Please vote/comment on #41 so that I can merge it. Three :+1: are required for a merge.

**Comment by sjackman** [comment]
@ilyaminkin If `TwoPaCo` is the only implementation of GFA1 containment `C` records, would you consider migrating to GFA 2 so that we can deprecate the containment record of GFA 1 of GFA 2's edge `E` records?

**Comment by ilyaminkin** [comment]
@sjackman does GFA2 specification exist somewhere? And what is the reason for deprecation of containment?

**Comment by sjackman** [comment]
GFA 2.0 is coming very close to a consensus. The PR is #48. Your comments are welcome.
If you are actively using GFA 1.0 containment `C` records in released code, then that's fine, we won't deprecate them. If however they were never implemented in released code, then I'd prefer to deprecate them.

**Comment by ilyaminkin** [comment]
I will take a look at the PR and let you know if I would stick to GFA1 or migrate to GFA2.

**Comment by ggonnella** [comment]
I do not understand, why it should be better to deprecate the C lines. They will not be there anymore in GFA2, but also the L lines will not: should we deprecate L lines too? That wouldn't make sense. C lines express things that cannot be expressed in other ways in GFA1.

**Comment by sjackman** [comment]
If `C` records had never been implemented by anyone, it would be better to encourage people to migrate to GFA 2.
