### ISSUE TITLE
[GFA2] About "dual" edges (was disallowing dual edges)

### ISSUE THREAD

**Issue by lh3** [GFA-spec/GFA-spec#35]
In GFA, an edge can be described in two ways e.g. `L sid1 +  sid2  +` vs. `L sid2 - sid1 -`. We call this _dual edges_. In #33, @pb-jchin requested to define whether we allow both edges to be present, as the current GFA1 spec seems not very clear about this point. In practice, I believe most existing GFA writers only write one of the dual edge, so we may make it formal: GFA2 only keeps one of the dual edges. Thus `L sid1 +  sid2  +` and `L sid2 - sid1 -` are considered as two [multiple edges](https://en.wikipedia.org/wiki/Multiple_edges) in GFA2 (though a particular implementation may choose to collapse multiple edges into one edge).

**Comment by sjackman** [comment]
I call the two representations complementary edges. I was a proponent for storing both edges in the graph file. ABySS does so with its Graphviz dot representation, and @pb-jchin does this as well with Falcon. I cannot find the discussion now in the archives.

After discussion, we decided that the graph

1. *must* store the canonical version of the edge, which is the orientation of the edge for which `sid1` is lexicographically smaller than `sid2`.
2. *may* also store the complementary edge, that is, both edges.
3. *must not* store only the non-canonical edge.

I prefer storing both edges, but I'm happy with the decision. I recommend we keep it as is.

**Comment by sjackman** [comment]
I was a proponent for storing both edges in the graph file. ABySS does so with its Graphviz dot representation, and @pb-jchin does this as well with Falcon. I cannot find the discussion now in the archives.

After discussion, we decided that the graph

1. *must* store the canonical version of the edge, which is the orientation of the edge for which `sid1` is lexicographically smaller than `sid2`.
2. *may* also store the complementary edge, that is, both edges.
3. *must not* store only the non-canonical edge.

I prefer storing both edges, but I'm happy with the decision. I recommend we keep it as is, unless there's an overwhelming majority to reverse the decision.

**Comment by pb-jchin** [comment]
@sjackman nice find. I do not there is a name of such graph until now.

**Comment by sjackman** [comment]
This issue has implications for random access to a GFA file. If you sort and index the link `L` records of a GFA file by the second column, a GFA file that stores both complementary edges will have all of the edges incident to any given vertex in a contiguous group in the sorted GFA file, whereas a GFA file that has only the canonical edges will have only an arbitrary subset of the edges incident to a vertex, those whose target vertex is lexicographically larger than itself.

**Comment by lh3** [comment]
Oh, I like this [skew-symmetric graph](https://en.wikipedia.org/wiki/Skew-symmetric_graph) and the fact that it is "identical to a bidrected graph". I wish I had known this earlier. Then I did not need to give such a graph a weird name in my miniasm paper. It is also interesting to know that determining such a graph is NP-complete.

Back to GFA, I think the definition of "canonical edge" is too strong. The graph representation should not depend on segment names. In addition, I don't think random access to edges is a required feature. This only works with one segment. When we need to extract a subgraph, we will have to perform many random jumps in the file to find all the edges anyway.

I still prefer to store one edge. An alternative is to have a header tag indicating whether complement edges are stored.

**Comment by sjackman** [comment]
> Oh, I like this skew-symmetric graph

:+1:

> Back to GFA, I think the definition of "canonical edge" is too strong. The graph representation should not depend on segment names.

There needs to be an arbitrary but consistent way of deciding which of the two edges is stored in the GFA file. We decided that the lexicographically smaller edge is an obvious choice, that is `min( (a,b), (b,a) )`. What do you suggest?

> When we need to extract a subgraph, we will have to perform many random jumps in the file to find all the edges anyway.

*n* jumps, where *n* is the number of vertices in the subgraph (say 100), is much better than reading the entire graph. Random access is not a necessary feature, but one to keep in mind I think.

> I still prefer to store one edge. An alternative is to have a header tag indicating whether complement edges are stored.

I'm fine with this, like the sorting `SO` header tag of SAM.

**Comment by sjackman** [comment]
I found this text down at the bottom of the current GFA spec:

> "Twin edges". A link can be represented in two directions. My preference is to allow both directions. The parser should throw a warning or an error if the two directions are inconsistent.

I'd be okay reducing the above to a recommendation:

1. *may* store either orientation of the edge.
2. *should* store canonical version of the edge, which is the orientation of the edge for which `sid1` is lexicographically smaller than `sid2`.
3. *may* also store the complementary edge, that is, store both edges.

**Comment by ekg** [comment]
I support leaving the written edge or edges as arbitrary choices of the
writer.

GFA like formats make sense for interoperability. However we should be
careful about baking in engineering decisions. If the feature set is too
complex then few will use the features and the ecosystem will be fragmented.

(I really don't want to think about indexing GFA directly!)

**Comment by rrwick** [comment]
I'm happy with any of the possibilities here and can make Bandage comply with the consensus.

For what it's worth, I dealt with this issue of defining a 'canonical' link some time ago in Bandage. Here's what I did there: If both segments in a link have the same sign, then the canonical version is the positive one. E.g. `L 8 + 4 +` is canonical, `L 4 - 8 -` is not. It is only when the segments have opposite signs that I used the lexicographic order to decide. E.g. `L 3 - 5 +` is canonical, `L 5 - 3 +` is not.

Also, a minor issue with lexicographical order: if segments are names with numbers, then `L 12 + 2 -` is the canonical link, not `L 2 + 12 -`. Does that matter? 

I mention these as options, but I don't feel strongly about them. If people think that straight lexicographic order is the simplest, I'm happy to go with that!

**Comment by rrwick** [comment]
Also, when a segment connects to its own complement, the link is _its own_ complement. E.g. `L 5 + 5 -`

Depending on the implementation, one might think of these cases as a dual pairs where both members are the same (e.g. `L 5 + 5 -` and `L 5 + 5 -`) or as a links lacking a dual... just something to keep in mind.

**Comment by rrwick** [comment]
And thanks, @sjackman, for teaching me the name 'skew-symmetric graph'!

**Comment by sjackman** [comment]
> For what it's worth, I dealt with this issue of defining a 'canonical' link some time ago in Bandage. Here's what I did there: If both segments in a link have the same sign, then the canonical version is the positive one. E.g. L 8 + 4 + is canonical, L 4 - 8 - is not. It is only when the segments have opposite signs that I used the lexicographic order to decide. E.g. L 3 - 5 + is canonical, L 5 - 3 + is not.

I'm happy with either definition. ABySS implements the simple lexicographical order, but I don't think it would break anything to change its definition. I can see benefits to your definition as well, for example when the graph has only positive/positive edges, it would remain that way after canonicalization. The simple lexicographical order definition is, well, simpler. Shall we wait for a third person to weigh in?

> Also, a minor issue with lexicographical order: if segments are names with numbers, then L 12 + 2 - is the canonical link, not L 2 + 12 -. Does that matter?

I prefer simple lexicographical order. An assembler can zero-pad the contig IDs to get sensible numerical ordering.

**Comment by sjackman** [comment]
On second thought, we need to define the sort order of the edges, and the simplest sort order of the two edges `e1` and e2` is the lexicographical sorting `(e1.u, e1.uori, e1.v, e1.vori) < (e2.u, e2.uori, e2.v, e2.vori)`. Under this sort order, I think the simplest definition of the canonical orientation of the edge is `min(e1, e2)`, so I stand by my original definition.

**Comment by lh3** [comment]
CC @pb-jchin.

Here is another idea to deal with "dual" edges, by changing the definition of L-lines. For an overlap like this:

![image](https://cloud.githubusercontent.com/assets/480346/18440066/bcc84c0c-78d5-11e6-90d1-ad35631776f4.png)

it is represented by two (new) L-line as:
```
L  sid1  +  sid2  +  o1  h1
L  sid2  -  sid1  -  o2  h2
```
Because o1/h1 may be different from o2/h2, we have to describe the overlap on two L-lines in the general case. Nonetheless, when o1=o2, including the case that both are zero, the (new) L-line may take a simpler form:
```
L  sid1  +  sid2  +  o1  *
```
The general rule is: 1) if the overhang length is present, both complement edges shall be present in GFA; 2) if the overhang length is absent (a "*"), only one L-line shall be present for the dual edge pair and the overlap length must be the same on both sid1 and sid2. The two forms of L may cause a bit complication in coding, but the duality will always cause complication, I believe.

What do you think?

**Comment by sjackman** [comment]
I prefer a symmetric definition of `L`.

**Comment by pb-jchin** [comment]
@lh3 
Please take a look at this plot. If we take the string graph point of view. In such case, we do associate "strings" from the sequences on the edges. 

If I understand correct (and I do use such convention in FALCON), here is the picture. I label 3 points on each segment. If we put the two segment on a line 1.X is the same as 2.B and 1.E is the same as 2.X. They are just different labelling.

![scr2016-09-12_09-37-33_am](https://cloud.githubusercontent.com/assets/1071734/18444066/8b27ae76-78cc-11e6-87aa-3d9824bf85f7.jpg)


The corresponding edges (associated with sequences) and the `L` record (without coordinate) is like this in my mind: 

```
edge1: (1.E/2.X -> 2.E) sequence from sid2  == L sid1 + sid2 + 
edge2: (2.B/1.X -> 1.B) sequence from sid1 == L sid2 - sid2 -
```

If you take this point of view, for the `L sid1 + sid2 +`, the more informative length is actually from `2.X` to `2.E`. If you agree with this, then instead of `o1  h1` for  `L sid1 + sid2 +`, it is better to use `o2  h2`. Between `o2` and `h2`, `h2` is more useful than `o2` as it does corresponding the length of the sequence associated with the edge.  I know this may not be intuitive, but it is best thing I have discovered during the development of FALCON since the concatenating sequences becomes 100% identical to concatenating the edges and I can totally forget the orientations during such operation. However, I do still have to make sure all operations preserve the skew-symmetry. Namely, I need to layout forward and reverse complement sequences at once.

**Comment by lh3** [comment]
@pb-jchin, what you said is all true: in the original string graph definition, edge1 is indeed `1.E --> 2.E` with length h2. Nonetheless, I personally found this is a little unusual: edge1 is "after" edge2. In miniasm, I modified the string graph a bit: edge1 in miniasm is `1.B --> 2.B` with length h1. I believe the modified string graph retains exactly the same properties of the original string graph. It works better in my head, though it may be just me.

> I prefer a symmetric definition of L

I think to common users and even many assembler developers, overlap graphs are easier to understand than string graphs. Nonetheless, after implementing both (fermi implements an overlap graph, while miniasm implements a string graph), I definitely like string graphs better. Just as you said, on a string graph, we can totally forget about orientations for a lot of operations as long as skew-symmetry is maintained. In contrast, on an overlap graph, I need 1-level deeper data structure and often have to test strands, which is a bit annoying.

@pb-jchin, I totally understand that you prefer h2 – miniasm would prefer h1 or h2, too. But thinking of the broader audience, I will use the current symmetric L-line (i.e. `L sid1 ori1 sid2 ori2 olen1 olen2`) for now. This decision is only temporary. I am open to changes in future. You see, I am wiggling between various choices myself. Thanks a lot!

**Comment by pb-jchin** [comment]
> Nonetheless, I personally found this is a little unusual: edge1 is "after" edge2. In miniasm, I modified the string graph a bit: edge1 in miniasm is 1.B --> 2.B with length h1. 

yes. it is equivalent. I probably should have labelled "edge1" and "edge1'" as the plot below:

![scr2016-09-12_11-28-25_am](https://cloud.githubusercontent.com/assets/1071734/18447561/0a7d7a2a-78dc-11e6-8275-c999761088d4.jpg)

And I see, the 1.E --> 2.E is a natural extension from 5' to 3' and the other `edgeX'` are those from 3' to 5'.  see the plot below:

![scr2016-09-12_11-30-15_am](https://cloud.githubusercontent.com/assets/1071734/18447654/723aef1c-78dc-11e6-9c09-bf9d5299ab55.jpg)

Any, like I say these are just 'conventions". In my ex-life as a physicist, the first thing that one reads a text book or a paper in electromagnetism / field theory / relativity is to figure out convention used. (see https://en.wikipedia.org/wiki/Sign_convention, yes, some people prefer imaginary numbers than "-1" and "+1" for good reasons.  ) After ~200 years of development of electromagnetism, it is still not "unified" but we live with it. (And I spent a good amount of time tracing the signs in equations for homework and taking home exam in grad school :) )

**Comment by sjackman** [comment]
ABySS implements a skew-symmetric overlap graph. It has two vertices for each segment (one for each strand) and two edges for each overlap (ditto). A helper class maintains skew-symmetry so that whenever vertex `A+` is removed, vertex `A-` is also removed. Ditto for edges, when `A+ -> B+` is removed, `B- -> A-` is also removed. I've found this convention quite convenient.

We all agree, I think, that the overlap graph can be interpreted as a string graph by the program reading the GFA file with relatively little trouble. All the necessary information is stored in the GFA.
