### ISSUE TITLE
Fieldnames in paths

### ISSUE THREAD

**Issue by ggonnella** [GFA-spec/GFA-spec#44]
In the current single-line path specification there is an inconsistency in the naming of some fields. The SegmentName field actually contain a list, so I think SegmentNames would be more appropriate (or OrientedSegmentNames, as they also contain an orientation).

Furthermore CIGAR is also singular, and indicates the format rather than the content - differently from L lines, to which the CIGAR actually refer to. Therefore I would use overlap instead of CIGAR, and pluralize this too, so "Overlaps".

I have created a pull request which fixes these issues (#43).

**Comment by sjackman** [comment]
Fixed by #43.
