### ISSUE TITLE
CIGARs, reference and query

### ISSUE THREAD

**Issue by ggonnella** [GFA-spec/GFA-spec#53]
CIGAR operations such as D and I require a sequence to be the reference, another to be the query.
The specification says that one can use CIGARs to express alignments (e.g. in L lines of GFA1, in E lines of GFA2). But it does not clearly state which segment (or segment overlap) is the reference and which segment is the query. I think we should add this to the spec.

**Comment by sjackman** [comment]
I agree we should add it to the spec. I agree with Heng @lh3:

https://github.com/GFA-spec/GFA-spec/pull/47#issuecomment-250615823
> For overlap CIGAR, I would take A as the reference and B as the query.

**Comment by ekg** [comment]
This still doesn't appear to be in the spec. Please re-open until it's fixed.

**Comment by sjackman** [comment]
Stalebot automatically closes issues that no one is actively working on. Feel free to open a PR if you would like to work on this issue.
