### ISSUE TITLE
Meaning should not depend on the order of records

### ISSUE THREAD

**Issue by sjackman** [GFA-spec/GFA-spec#54]
I propose to strike the text

`U/O-lines with the same name are considered to be concatenated together in the order in which they appear, and`

See its context here under the heading [Group](https://github.com/thegenemyers/GFA-spec/blob/13803517e2ac4c981d695a518e850e023e702170/GFA2-spec.md#group).

The meaning of a GFA file should not depend on the order of its records. It should be possible to sort or shuffle a GFA file without affecting the meaning of the GFA file. Imagine if the meaning of a SAM file depended on the order of the alignments in the SAM file. Sorting by read name or target position would not be possible.

Consider the following example of `O P1 2+ 1+` with split across two lines:
```
O P1 2+
O P1 1+
```
after a UNIX `sort` it becomes
```
O P1 1+
O P1 2+
```
which has changed the meaning of this path `P1` from `2+ 1+` to `1+ 2+`.

**Comment by sjackman** [comment]
@ekg @ggonnella @jts @lh3 @pb-jchin @rchikhi @richarddurbin @rrwick @sjackman @thegenemyers
Your vote on this proposal is appreciated.

**Comment by sjackman** [comment]
This text was added to address Erik's use case of walks. His use case specifically included sorting the path records by their components, and so I believe text does not address use case, and as such should be removed.

Erik's use case should I feel be addressed with a new walk record type. Heng Li proposed such a record at https://github.com/GFA-spec/GFA-spec/pull/47#issuecomment-250615823. I suggest we define such a record type with a future backward-compatible revision of GFA (e.g. GFA 2.1), guided by Erik and that specifically addresses his use case.

**Comment by rrwick** [comment]
I vote in favour of this proposal!

**Comment by ggonnella** [comment]
I am not against your proposal of deleting the quoted text (i.e. I am rather neutral on this).

As GFA2 allows for user-specific line types (ignoring by a core parser anything which is not starting with the standard record type specifiers), we should decide if the W line shall be an application-specific line or if it shall really be included in a future specification.

**Comment by sjackman** [comment]
I'm inclined to defer that question to a future date. More immediately I think it's quite important that we resolve that the meaning of a GFA file should not depend on the order of its lines. The walk record could start as application specific, and be proposed using a pull request for adoption by the standard. The benefit of an extensible standard is that we don't have to nail down every possible application right away.

**Comment by thegenemyers** [comment]
Shaun,

    I don't really understand the use-case that is being discussed. I 
read the 'W' line
description and it does not convey to me the precise meaning.

    A path can be in pieces, i.e. on different lines, and still be 
reconstructed with
the understanding that edges between path pieces are not inferred, which 
is the
case in your rather extreme example.  For example,

O blue V3 V4 V5
O blue V1 V2 V3
O red e34 35
O red e12 e23

work just fine.

     I'm not sure why order independence is important, nor what it buys 
you.  Basically, the
way the standard is currently you have to read the entire file to now if 
its even valid, i.e.
there are no undefined vertices, etc.  If you are going to read the 
whole file (sequentially)
and build an internal representation in response to semantically check 
it, etc. then ???

    -- Gene

**Comment by rrwick** [comment]
Gene,

Using your 'blue' example, if this is the full graph structure...

<img width="222" alt="screen shot 2017-01-14 at 12 12 42 am" src="https://cloud.githubusercontent.com/assets/7053555/21931192/334cf606-d9ee-11e6-9077-02ead4f93180.png">

...then this path is V3 -> V4 -> V5 -> V1 -> V2 -> V3:
```
O	blue	V3 V4 V5
O	blue	V1 V2 V3
```

...and this path is V1 -> V2 -> V3 -> V3 -> V4 -> V5:
```
O	blue	V1 V2 V3
O	blue	V3 V4 V5
```
Both paths are valid, so it seems like the definition does depend on the line order. I guess I'm unsure of what you mean by 'work just fine'. Am I missing something?

**Comment by thegenemyers** [comment]
No, I wrote that if we define it so that one *does not* infer edges 
between line components
then it is order dependent.  So the path is V1->V2->V3->V4->V5.  The 
reference to V3
twice connects the two segment in an unambiguous way.  If eij is the 
edge Vi->Vj, then the
red path also defines the same path.
    -- Gene

**Comment by thegenemyers** [comment]
If you put one vertex per line.  If you wrote

O blue A X B
O blue B Y C
O red A Y B
O red B X C

it would be fine and you still have the convenience of not having to have
a line with 20,000 vertices on it (for example, some paths in real graphs
are really that long with PacBio tech).

    -- Gene

**Comment by rchikhi** [comment]
The discussion boils down to whether the following lines

> O blue A B 
> O blue B C

encode the path A ->B ->B -> C  or the path A ->B -> C.  Which is it?

**Comment by rchikhi** [comment]
Anyhow I vote in favor of the proposal. It wouldn't be very elegant if the order of the lines inside a GFA2 file mattered just because of those O/U-lines.

**Comment by rrwick** [comment]
I understand better now, but even if separate lines of a path must share a segment (as Gene and Rayan said) the line order can still matter.

Here's the simplest case I can think of:
<img width="93" alt="screen shot 2017-01-14 at 8 46 15 am" src="https://cloud.githubusercontent.com/assets/7053555/21946840/519c24c2-da36-11e6-8bcd-cb3d0d09b2d5.png">

This path is V1 -> V2 -> V1 -> V3 -> V1:
```
O	blue	V1 V2 V1
O	blue	V1 V3 V1
```
And this path is V1 -> V3 -> V1 -> V2 -> V1:
```
O	blue	V1 V3 V1
O	blue	V1 V2 V1
```

Complexities like this feel awkward, so I'm still in favour of the proposal to require groups to be defined on one line.

**Comment by sjackman** [comment]
My count of the votes is
Strike the text: @rchikhi @rrwick @sjackman
Keep the text: @pb-jchin @thegenemyers
Abstain: @ggonnella
@lh3 @rricharddurbin Do you wish to vote on this proposal?
Unless anyone else speaks up, the proposal to strike the text is accepted. We can of course address this use case again in a future proposal.

**Comment by richarddurbin** [comment]
I am frustrated because as far as I can see everyone has voted to accept the standard, which should mean that they take it as is.  But somehow at the same time a subset have argued to change it, which is incompatible with accepting it as is.

That said, I hear the concern about order dependence.

So here is a proposed way forwards. Rather than remove all mention of the multiline idea, we remove it from the current formal syntax specification, but in the descriptive text for the group lines in the official spec document we say that there was discussion about allowing multiple group lines with the same identifier which would define consecutive segments of an ordered group, and that this was not included in the current version, but that if people want to explore use of this structure they could do so using another single letter record code.  This would permit compatible exploration, since I understand that records with letters outside the current set get ignored by a formal parser.  If someone does explore multiline groups this way and makes a case for them, with current syntax or a variation of that, then we can debate how to incorporate that into the official spec.

I like this approach because I don’t want all mention of this idea to be lost from the specification document.

Richard

**Comment by sjackman** [comment]
I'm fine with moving the multiline path discussion to a non-formal descriptive text. A multiline path could be useful, but I think its format needs more discussion.

**Comment by sjackman** [comment]
I've added the following text:

Note: It was discussed whether U/O-lines with the same name could be considered to be concatenated together in the order in which they appear (see #54 and #47). This multi-line path format was not included in the current version of this specification, but if people want to explore use of this structure, they can do so using a different single letter record code.

**Comment by thegenemyers** [comment]
I'm OK with this and with the text that Shaun put in as a place-holder 
for the
discussion.
    -- Gene

**Comment by ggonnella** [comment]
If we allow a multiline path at some point, one could code the order with an optional tag, only included in multilne paths. I do not see any disadvantages in that case, other than some more validation checks (is the tag included in all lines with the same ID? are the tags values all different? is the encoded path resulting from the concatenation a valid one?).
