### ISSUE TITLE
IDs namespace in GFA1

### ISSUE THREAD

**Issue by ggonnella** [GFA-spec/GFA-spec#56]
The namespace of IDs in GFA2 is clearly identified: S,E,G,U,O line identifiers all belong to the same namespace, while the external sequence identifiers in F lines do not.

However, this problem is not explicitly addressed in GFA1. In most examples I found, the S and P have different IDs.

My proposal is to add a statement to the GFA1 specification, and declare that P and S names (as well as the optional IDs in L and C lines, if #55 is accepted) belong to the same namespace. This is what I assumed in gfapy, I think it is reasonable and helps interconversion to/from GFA2. Would this break any existing implementation?

**Comment by ggonnella** [comment]
@edawson I noticed that in gfakluge there is one file  in which P and S use the same namespace https://github.com/edawson/gfakluge/blob/master/data/q_redundant.gfa - The file is anyway non-standard GFA, and uses a custom P syntax. If I got it right, you are switching it to custom walk W lines?

**Comment by sjackman** [comment]
:+1: I agree, one namespace is good.

**Comment by edawson** [comment]
That's correct, @ggonnella , though I'd say that file is valid GFA "0.1," which is what I've taken to calling the version originally proposed by Heng. I think I pulled it directly from Heng's blog.

GFAKluge permits reading/writing the 0.1-style `P` lines, the custom `W` lines we hope to incorporate in GFA 1.1, and P lines as implemented in GFA 1.0.

**Comment by ggonnella** [comment]
Recently I had another example of file, from TwoPacCo, which output GFA reusing the name of some segments as paths. My tools (RGFA, GfaPy, GfaViz) do not consider the output valid GFA currently.

I asked this previously, but the proposal of specifying that the namespace is the same for S and P was not implemented and after some time closed. So now I am now unsure if to change this behavior in my tools or insist again in trying to get this enforced.

**Comment by sjackman** [comment]
Have you opened a PR to this effect? When you do, we can vote on the proposed text.
