### ISSUE TITLE
[GFA1] C line description is ambiguous

### ISSUE THREAD

**Issue by ggonnella** [GFA-spec/GFA-spec#57]
In the GFA1 specification, the description of C lines is ambiguous. It is written that "A containment line represents an overlap between two segments where one is contained in the other.". However, nowhere is actually written which segment is contained in which one; the two segments are called "from" and "to", which does not really make clear, which is the container and which is the contained segment. Until recently, I supposed that "from" is the container and "to" the contained segment (either from an old version of the spec, or from examples, I suppose), but this is not actually stated in the text.

**Comment by richarddurbin** [comment]
I also was not sure of the direction of this relationship when reading the spec to write a GFA1 to GFA2 converter.  Please clarify in the GFA1 spec, ideally with an example.

Richard

**Comment by ggonnella** [comment]
I posted PR #58 which addresses this issue.

**Comment by ggonnella** [comment]
The PR also specifies more clearly, what shall be stored in the Pos field.

**Comment by sjackman** [comment]
Fixed by PR https://github.com/GFA-spec/GFA-spec/pull/65
