### ISSUE TITLE
GFA1.0 Path line segment/orientation order is unclear

### ISSUE THREAD

**Issue by edawson** [GFA-spec/GFA-spec#59]
I've run into some GFA files that my parser cannot parse because the orientation comes before the segment name, and isn't specified at all if its in the forward direction. This made me realize that the spec itself does not specify if orientations come before or after segment names. It simply says:
    
    SegmentNames String [!-)+-<>-~][!-~]*  A comma-separated list of segment names and orientations

"Comma-separated list" is ambiguous as to order. Can we clarify if this is required to be as in the example?

    P	14	11+,12-,13+	4M,5M

And whether they must be present, regardless of orientation? Perhaps the description should be come "A comma-separated list of concatenated segmentName / orientation pairs, one for each segment. Both elements are required."

I am happy to make a PR once this has been discussed.

**Comment by sjackman** [comment]
Yes, your interpretation is correct. The orientation is required. I suggest:

> A comma-separated list of pairs of a segment name and orientation. The orientation is required.

And add `[-+]` to the regex: `[!-)+-<>-~][!-~]*[-+]`
