### ISSUE TITLE
[GFA1] Representing paths with gaps (e.g. scaffolds)

### ISSUE THREAD

**Issue by snurk** [GFA-spec/GFA-spec#60]
Sorry if this issue has already been discussed somewhere, but is there a good way for representing a path, corresponding to a "scaffold" within GFA 1?
Since Paths can only go through the linked segments, we currently break a scaffold adding suffixes to the names of the subpaths.
But we do not like this solution. We probably could use Walks extension suggested by @ekg here, but I am not sure if it is within their intended scope and whether those records will be adopted within the community.

**Comment by sjackman** [comment]
I was considering proposing that we use a CIGAR string of `123N` to represent a gap of 123 Ns between to segments. Your thoughts?

**Comment by sjackman** [comment]
Have you considered migrating to GFA2? I'd prefer not to add new features to GFA1, except to improve compatibility with GFA2.

**Comment by snurk** [comment]
I like 123N notation. It will imply necessity to add auxiliary links to the graph, representing information inferred during scaffolding, rather than obtained directly from sequences. But it actually might be a good thing.

**Comment by sjackman** [comment]
Have you considered migrating to GFA2? It has gap edges, which can be used in paths.

**Comment by snurk** [comment]
We will definintely add GFA2 support soon and will gradually try to use its awesome extended features to encode a lot of potentially useful information. 
It is pretty straightforward to produce output in any reasonable format, but my personal concern is that the richer the format -- the more ways there are for assemblers to use it, and the harder it might be to write applications to process the results of different assemblers :)
I like that GFA1 is relatively simple, while expressive enough to represent important features of graph-based assembly.
Until decent gene finder, sequence mapper, etc are implemented over GFA2, I would try to maintain comprehensive GFA1 support in case someone decides to implement them over the simpler format.

**Comment by snurk** [comment]
So is there a chance that 123N notation will become a part of the specification? 
Alternatively I could probably use 0M as a special value for gaps of arbitrary size.

**Comment by sjackman** [comment]
`0M` is a special value that means specifically that the two sequences are abut with no overlap or gap.

You can open a pull request against `GFA1.md` to propose adding this `123N` notation to GFA 1. The criteria for merging a pull request are at https://github.com/GFA-spec/GFA-spec/issues/16

You could also produce a GFA file with a non-standardized user-specific path record, such as the lower case `p`, with the inherent limitation that those records would only work with your tools and be ignored by other tools.

Finally, you can produce GFA 1 files without scaffold gaps for use with GFA 1 software like Bandage, and GFA 2 files with scaffold gaps. I'm not familiar with any GFA 1 tools that use path `P` records, so there may be little downside to this option.

**Comment by snurk** [comment]
Thank you for this exhaustive answer!
I will try to prepare a pull request and will use one of the remaining options for SPAdes if it will be rejected.
