### ISSUE TITLE
[GFA2] Why is distance in Gap line is 'pos' instead of 'int'

### ISSUE THREAD

**Issue by eshcherbin** [GFA-spec/GFA-spec#61]
Hi!
Could you clarify why the distance field in a G-line should be of type `pos` rather than `int` according to the Grammar section of the [specification](https://github.com/GFA-spec/GFA-spec/blob/master/GFA2.md)? Is that a mistake?
Thanks!

**Comment by sjackman** [comment]
That looks like a mistake to me, Egor. I believe it should be an `int`. Feel free to open a pull request to fix it.

**Comment by eshcherbin** [comment]
PR #62 opened.

**Comment by sjackman** [comment]
Superseded by #62.
