### ISSUE TITLE
[GFA2] Typos and wrong example

### ISSUE THREAD

**Issue by ggonnella** [GFA-spec/GFA-spec#64]
@stefan-kurtz recently noticed that in the GFA2 specification, the example in the  "Edge" section is wrong, as it uses an "S" record instead of "E", as it should be. I fixed this, as well as four typos I found in the spec in a new pull request (#63).

**Comment by sjackman** [comment]
Fixed by https://github.com/GFA-spec/GFA-spec/pull/63
