### ISSUE TITLE
How to extract assembly from gfa file?

### ISSUE THREAD

**Issue by nottwy** [GFA-spec/GFA-spec#66]
I have a simple question:

After I get a gfa file, how can I get the assembly of the genome I want?

Someone said all segment sequences in the S lines are my assembly result. Is it correct?

**Comment by sjackman** [comment]
Yes, that's correct. For GFA 1.0
```sh
awk '/S/ {print ">" $2 "\n" $3}'
```
for GFA 2.0
```sh
awk '/S/ {print ">" $2 " LN:i:" $3 "\n" $4}'
```
Also check out Gfapy https://github.com/ggonnella/gfapy
@ggonnella Does Gfapy have a command to convert GFA to FASTA?

**Comment by ggonnella** [comment]
Sorry, somehow I did not notice your question. Probably too late, but I answer for completeness.

Yes, you can extract the sequences with gfapy and convert them to Fasta with a very short python program. 
```
import gfapy
gfa = gfapy.Gfa.from_file(filename)
for s in gfa.segments:
  if s.sequence:
    print(">{} LN:i:{}\n{}".format(s.name, s.length, s.sequence))
```

This is valid for both GFA1 and GFA2. Of course one can also easily include other conditions, to output just a part of the sequences (e.g. `if len(s.sequence) > 1000`).

**Comment by edawson** [comment]
You can do this with [gfakluge](https://github.com/edawson/gfakluge) from the command line:
`gfa_extract <my_gfa_file> > my.fasta`

You can also concatenate Sequences in Paths (for example, when your contigs are paths in a graph rather than plain sequences):
`gfa_extract -p <my_gfa_file> > my.fasta`

**Comment by sjackman** [comment]
Nice. Thanks, Eric!

**Comment by nottwy** [comment]
@sjackman 
The method you proposed is not suitable for the output of miniasm (https://github.com/lh3/miniasm) where 'S' may appear at other place not the beginning of a line.
It's better to require that 'S' must be at the beginning of a line.
Like this:
awk '/^S/ {print ">" $2 "\n" $3}'

Thank your for your help.

**Comment by sjackman** [comment]
Thanks for catching my error, Nott. I've corrected my post: https://github.com/GFA-spec/GFA-spec/issues/66#issuecomment-322833367
