### ISSUE TITLE
Describe Link with GFA2 Edges

### ISSUE THREAD

**Issue by dlobba** [GFA-spec/GFA-spec#68]
I'm trying to understand Edge lines that describe GFA1 Links.
While reading the following sentence:
> The GFA2 concept of edge generalizes the link and containment lines of GFA. For example a GFA edge which encodes what is called a dovetail overlap (because two ends overlap) is a GFA2 edge where either beg1 = 0 or end1 = x$ and either beg2 = 0 or end2 = y$.

I realized that situations like:
`E l12 1+ 2+ 0 3 0 3 *`
would be considered as dovetail overlaps. But I think that this situation represents a general
overlap (correctly described by a GFA2 Edge but impossible to be represented by a GFA1 Link).

Could the sentence above be reformulated as follow:
> For example a GFA edge which encodes what is called a dovetail overlap (because two ends overlap) is a GFA2 edge where either beg1 = 0 **and** end2 = y$ or either beg2 = 0 **and** end1 = x$ .

**Comment by sjackman** [comment]
> either beg1 = 0 and end2 = y$ or either beg2 = 0 and end1 = x$

That describes a containment edge rather than a dovetail edge.

The dovetail overlap `E l12 1+ 2+ 0 3 0 3 *` in GFA 1 is `L 1 - 2 + *`.
