### ISSUE TITLE
Pan-Genome Graphs

### ISSUE THREAD

**Issue by ilyaminkin** [GFA-spec/GFA-spec#7]
There is some recent work on using of de Bruijn graphs on analysis of pan-genome, e.g. see:
1. http://biorxiv.org/content/early/2014/04/06/003954
2. http://link.springer.com/chapter/10.1007/978-3-319-19929-0_4
3. http://link.springer.com/chapter/10.1007/978-3-642-40453-5_17#page-1

So far, there is no common format for such graphs. Does it make sense to generalize GFA to handle both pan-genome/assembly graphs?

**Comment by pmelsted** [comment]
I think this makes perfect sense and it's quite easy to do.

For each segment you can annotate each segment with a tag indicating which genomes contain that segment.

e.g.

```
S 0 GAT TN:Z:Human
S 1 CCC TN:Z:Mouse
S 2 TAC TN:Z:Human,Mouse
S 3 A TN:Z:Human
S 4 TTA TN:Z:Mouse
L 0 + 2 + 0M TN:Z:Human
L 1 + 2 + 0M TN:Z:Mouse
L 2 + 3 + 0M TN:Z:Human
L 2 + 4 + 0M TN:Z:Mouse
```

in this case I've used the tag `TN` for `Target Name` to annotate both the segments and optionally the links used by each genome.

**Comment by ilyaminkin** [comment]
Thank you, sounds good.

**Comment by sjackman** [comment]
I think that it would be helpful to the parser to declare the possible values of `TN:Z` in a header line. Perhaps 
`H TN:Z:Human`
`H TN:Z:Mouse`

**Comment by sjackman** [comment]
@ilyaminkin Please open a pull request proposing this tag, if you like.

**Comment by ilyaminkin** [comment]
Oops, it seems that I have some misunderstanding. Are all tags supposed to be "hardcoded" in the specification, or it is possible for a user to introduce their own tags?

**Comment by sjackman** [comment]
The user can introduce tags that are composed of two lower-case characters. Upper-case tags are reserved for standardized tags. You can freely use lower-case characters.

I've taken text from the SAM spec describing optional fields. See 99811a24a5f17b8f7bfa874ebce53a9b20a31a98

**Comment by pmelsted** [comment]
The idea is to standardize as many of the tags as possible and nail down the semantics. The SAM spec also has `X,Y and Z` flags which are implementation specific.

**Comment by sjackman** [comment]
> The SAM spec also has X,Y and Z flags which are implementation specific.

I prefer to use only lower-case for non-standard attributes and leave `[XYZ]?` available for standard attributes.

**Comment by sjackman** [comment]
> The idea is to standardize as many of the tags as possible and nail down the semantics.

And yes, I agree. If your implementation of GFA requires a particular attribute, there are probably others that require the same attribute, and it's worth the time to create a pull request to standardize it, I believe. That being said, the implementation should come first, I think, to avoid standardizing attributes that never end up getting used by an implementation.

**Comment by ilyaminkin** [comment]
> The idea is to standardize as many of the tags as possible and nail down the semantics.

I see. 

> That being said, the implementation should come first to avoid standardizing attributes that never end up getting used by an implementation.

That is true. I will definitely make a pull request. However, I have to think very well about proposed additions, there should be a little bit more than the species that contains the segment. I'm developing this kind of tool (de Bruijn graph constructor for pan-genome), so I'm interested in using this format as smoothly as possible.

**Comment by ekg** [comment]
I would rather list which elements are part of a set. As will be done for
paths.

**Comment by noporpoise** [comment]
It would be good if we could give the coverage in each sample for multi-sample graphs. For example a graph of three humans might look like this:

    S 0 GAT SC:B:21,0,12
    S 1 CCC SC:B:0,100,32
    ...

This example uses `SC` for `Sample Coverage` and the `B` data type from the SAM format for an array of integer or numeric values. I'm not sure how you'd specify sample details in the header. 

The same principle could be used for pan-genome graphs.

**Comment by ekg** [comment]
The more nested and implicit the annotations are the more complex merging
and comparing data becomes. This has been a major problem with VCF and
frankly my patience is pretty worn after having spent years maintaining a
parser and toolchain based around it.

Some thought is warranted before we build a new semistructured format.
Design decisions like whether things are row or column-oriented make a big
difference in how easy it is to work with the data. For instance, if each
sample/node/coverage annotation were expressed on a separate record merging
will be as simple as concatenating files.

I am very reluctant to implement GFA if it becomes any more complex than a
tabular (columnar) format. We already have JSON and exactly equivalent
binary formats in vg. These were extremely easy to set up.

What I'm looking for is the bare minimum required to exchange a graph
between an assembler, an aligner, and a variant caller. If we want
something more complex maybe we should step back and look at more generic
ways to make structured formats.

As a concrete proposal I suggest we allow arbitrary annotations at the end
of records, but do not standardize any. This way I can stash JSON in there
and Isaac can put VCF/SAM-like data in. I think it is really important to
keep the standard simple, or we will begin making work for ourselves.

**Comment by pmelsted** [comment]
I agree that the standard should be kept simple. One of the key features is that it should be 'awkable' (yes that's a word), i.e. if you are looking for a particular piece of information it should be in a location that is predictable, e.g. to find all segments linked with id `0` you would do

`awk '{if($1=="L" and ($2==0 or $3==0)) { print $0}}`

I like the idea of having non-standardized arbitrary info in the last columns. This would remove the need for having too many tags.

On the other hand I think we should focus on a few core applications, namely: assembly graphs (as output by assemblers), pan-genome graphs, sequence variation graphs and long-read overlap graphs. Any tags or features should indicate which of these applications need them and for which they could be applicable.

**Comment by noporpoise** [comment]
I would really like JSON annotatations. Something like this:

    S 0 GAT {"SC": [21,0,12]}
    S 1 CCC {"SC": [0,100,32]}

or the user could be more explicit:

    S 0 GAT {"NA12878": 132, "mouse": 0}
    S 1 CCC {"NA12878": 21, "mouse": 101}

Advantages:
* simple to represent structured data
* easy to merge JSON annotations
* many libraries exist to handle the data

I suggest the format allows 0 or 1 arbitrary JSON entries at the end of the line. If we allow ANY annotation a generic merge operation becomes impossible.

**Comment by pb-jchin** [comment]
I agree with @ekg. also, if the GFA's first priority is to represent assembly, I would argue the associations between links and contigs is probably more essential than the association to samples.  Even the association to contigs can be done by external references.

**Comment by sjackman** [comment]
@noporpoise I *love* the idea of making the last column of every record JSON. :+100:

**Comment by sjackman** [comment]
I'm going to open an issue to discuss the JSON proposal.

**Comment by sjackman** [comment]
I've opened a proposal to add a JSON type `J` in #18.

@noporpoise Your multi-sample `SC` could look like this:

```
S 0 GAT SC:J:{"NA12878": 132, "mouse": 0}
S 1 CCC SC:J:{"NA12878": 21, "mouse": 101}
```

or perhaps

```
S 0 GAT JS:J:{"SC":{"NA12878": 132, "mouse": 0}}
S 1 CCC JS:J:{"SC":{"NA12878": 21, "mouse": 101}}
```

**Comment by ilyaminkin** [comment]
I'm going to implement a GFA for the pan-genome graph very soon. The only thing that is needed is an optional for segments with an array containing all occurrences of a segment in genomes, a JSON record would be perfect for that. So:

1) I see that JSON pull request is not merged yet, what is the status of that?
2) Is it worth standardizing a tag that contains data described above (i.e. occurrences)?
3) Should the standard specify the encoding of coordinates within JSON, i.e. whether it is 0-based or 1-based and so on?

**Comment by ekg** [comment]
What format is the graph in now?

**Comment by ilyaminkin** [comment]
I'm developing TwoPaCo: https://github.com/medvedevgroup/TwoPaCo

The code is not released yet, currently it has an internal ad-hoc format and its text version, but I need something more adequate for the release. Other tools use DOT, and I find it quite clumsy.

**Comment by edawson** [comment]
It would be relatively simple to implement your own string-type tag (as described above) for a list of occurrences if it avoided using colons in the key field (e.g. oc:Z:human 46; mouse 40; dolphin 44]). [VG's parser](https://github.com/edawson/gfakluge) should already support reading and storing this string. It's up to you to parse the key as you wish then.

Aside w.r.t. JSON: If a JSON type gets added to the spec I'm happy to parse it in this manner (as a string key), but I don't want to store JSON objects, add an outside dependency or force my favorite JSON parser on everyone.

**Comment by pmelsted** [comment]
I always had some doubts that including a JSON tag would be too much, but now I see that it is probably the best solution for "free format" data that can't go into regular tags.

Regarding the Pan Genome question I think it would be good to settle on a schema for the JSON tag. For each segment we require the following information for any genome containing that segment,
1. chromosome
2. position
3. strand

Technically this should be a vector of such items that represent a mapping of the segment to the target genome. The question is whether it is useful to retain this information, or just project it down to whether the segment occurs or not.

An example of the full format would be

```
H   VN:Z:1.0
S   11  ACCTT PG:J:{
  "Human": [{ "target":"chr1", "pos": 1500, "strand": true }],
  "Mouse": [{ "target":"chr2", "pos":2000, "strand":false }]
  "ecoli": [{ "target":"chr1", "pos":2000, "strand":false }, {"target":"chr1", "pos":3000, "strand"=true}]
}
S   12  TCAAGG
S   13  CTTGATT
L   11  +   12  -   4M
L   12  -   13  +   5M
L   11  +   13  +   3M
P   14  11+,12-,13+ 4M,5M
```

The newlines in the JSON datatype are added for readability only, the proposed spec bans them to simplify parsability. So in this example we have a segment that is unique in two genomes and repeated in on of them.

I think retaining this information is better since it would allow other tools to use the GFA result from builders of Pan Genomic graphs.

**Comment by ilyaminkin** [comment]
> Technically this should be a vector of such items that represent a mapping of the segment to the target genome. The question is whether it is useful to retain this information, or just project it down to whether the segment occurs or not.

This information should be 100% retained, otherwise it would be hard to readily implement comparative genomics application using GFA from Pan Geomics graph builders.

A concern that I have is whether the occurrences list should be two-level, i.e. contain information about genomes. Many tools work with a bunch of FASTA-files only distinguishing sequences by IDs in FASTA headers without "attaching" them to genomes. So the results in @pmelsted's example would look like:

H   VN:Z:1.0
S   11  ACCTT PG:J:{[{ "target":"human_chr1", "pos": 1500, "strand": true },
{ "target":"mouse_chr2", "pos":2000, "strand":false }, { "target":"ecoli_chr1", "pos":2000, "strand":false }, {"target":"ecoli_chr1", "pos":3000, "strand"=true}]}

Which option fits better for standardization?

**Comment by sjackman** [comment]
I've merged my proposal to add a JSON type `J` in #18, discussed in #15.

**Comment by lh3** [comment]
I am supportive of having a new `J` type for values in JSON. On pan genomes, I think I more like @pmelsted's version. We should not make assumptions on sequence names. Another option is like this:
```
H   VN:Z:1.0
S   11  ACCTT PG:J:{[{ "target":"chr1", "pos": 1500, "strand": true, "species":"human" },
{ "target":"chr2", "pos":2000, "strand":false, "species":"mouse" }, { "target":"chr1", "pos":2000, "strand":false, "species":"ecoli" }, {"target":"chr1", "pos":3000, "strand":true,"species":"ecoli"}]}
```
I don't have a strong opinion on this topic.

**Comment by sjackman** [comment]
Rather than a `species` tag, I'd suggest a `file` tag to indicate in which FASTA file to find the named `target`.

**Comment by ilyaminkin** [comment]
@sjackman Yes, that makes more sense to me.

**Comment by ilyaminkin** [comment]
Another option is instead of having JSON for each segment, have occurrence lines for them, like

S 3 ACTA
O 3 chr1 42 true
O 3 chr2 9000 false

**Comment by ilyaminkin** [comment]
Hi all,

As @sjackman suggesed during HitSeq, an even better solution for this is to use the existing "Containment" line. For the example above:

S 3 ACTA
C 3 + chr1 + 0 4M SRC:Z:hg38.fa
C 3 + chr1 + 3 4M SRC:Z:hg38.fa

It only requires to modify the definition of the containment line so that it captures this use case. One thing that should be added is an optional tag (SRC) for source of the chromosome, as suggested above. I made a pull request with those slight changes. The only issue is that the resulting file is going to be quite bulky.

**Comment by pmelsted** [comment]
I like this solution. 

The file becomes bulky in terms of lines, but should be similar to the proposed JSON solution in terms of bytes.

**Comment by sjackman** [comment]
Note that the tag `SRC` must be exactly two characters.

**Comment by sjackman** [comment]
Rather than a source tag for every containment record, I would prefer to add a header line that indicates that sequence `chr1` comes from the FASTA file `hg38.fa`.

**Comment by sjackman** [comment]
See this relevant comment of mine:
https://github.com/rrwick/Bandage/issues/23#issuecomment-215143725
> When the sequences are missing from the GFA file, it would be helpful to include a header line that points to the associated FASTA file(s), along with their SHA1/SHA256, similar to what the SAM/BAM spec does with the @SQ UR and M5 header tags for reference sequences (which are not included in a SAM/BAM file). Rather than one tag per sequence, I'm intending one header per FASTA file. I'm going to submit a PR to the GFA spec requesting this addition. Do you have any comments before I do?

I never did submit that PR.

**Comment by ilyaminkin** [comment]
> Rather than a source tag for every containment record, I would prefer to add an optional field of the segment header line S that indicates that sequence chr1 comes from the FASTA file hg38.fa.

That makes sense to me.

> I never did submit that PR.

Do you have a ready PR to submit or I just have to move the `SC` tag to "Segment" line?

**Comment by sjackman** [comment]
No, I do not have a PR ready. Can we use `UR` for an URL instead? A file path is also a valid URL.

**Comment by ilyaminkin** [comment]
>  Can we use UR like SAM/BAM for an URL instead?

I think that consistency with other format(s) is a good thing.

> I'd prefer to use SHA-256 rather than MD5.

Let's hear other's opinions.
