### ISSUE TITLE
Add SPAdes to GFA1 section

### ISSUE THREAD

**Issue by asl** [GFA-spec/GFA-spec#73]
SPAdes generates assembly graph in GFA format and paths traversed by scaffolds over it.

**Comment by sjackman** [comment]
Thanks, Anton. Fixed by https://github.com/GFA-spec/GFA-spec/commit/b3005b856ea4e3451f8952fb94bfb3b8558ca181
Any thoughts of adding GFA 2 support to SPAdes?

**Comment by asl** [comment]
Not yet, but we may consider this later :)
