### ISSUE TITLE
README URLs need formatting

### ISSUE THREAD

**Issue by evanbiederstedt** [GFA-spec/GFA-spec#76]
The URLs at the bottom of the current REAMDE, i.e. 

> GFA 1 was first suggested in a blog post by Heng Li (@lh3) and further developed in a second post.

are currently broken. The hyperlinks send users to 

http://lh3.github.io/2014/07/19/a-proposal-of-the-grapical-fragment-assembly-format/
http://lh3.github.io/2014/07/23/first-update-on-gfa/

This should be changed to 

http://lh3.github.io/2014/07/19/a-proposal-of-the-grapical-fragment-assembly-format
http://lh3.github.io/2014/07/23/first-update-on-gfa

Thanks

**Comment by sjackman** [comment]
Fixed. Thanks for the bug report, Evan!
