### ISSUE TITLE
alignments to graphs

### ISSUE THREAD

**Issue by ekg** [GFA-spec/GFA-spec#79]
In [vg](https://github.com/vgteam/vg) we use GFA for input and output. It's completely lossless with respect to the graph model, and we need only S, L, and P namespaces to represent the graph. However, there is no textual analog to SAM provided in the GFA format space. We do have cigars applied to edge overlaps and the fragment records in GFAv2. But these seem to be limited to the mapping between a read and a single sequence-containing node in the graph.

We could use Paths in GFAv1 to specify alignments, but there is no standard place to add sequences to these (which is helpful for various processing operations) or clear if an extended CIGAR can be used which we can use to reproduce the sequence of the Path using the node Sequences in the graph. Are others using Paths to represent alignments?

Alignments are useful in resequencing, when we consider the graph as a reference system. But there are other, more fundamental uses that should be considered. We can build graphs progressively with operations *align* and *edit*, that map new sequences into the graph and update the graph to include them. Tools that implement these functions can be chained together to make custom assembly pipelines. We could do this all within a coherent data model in GFA provided a SAM or PAF-like alignment schema.

Variations against a graph can also be represented as alignments, and genotypes represented as collections of these at an overlapping bubble (or other generalized site-like entity in the graph). Standard models for variants, genotypes, and bubbles would be a nice thing as well, but that's another conversation.

**Comment by lh3** [comment]
GFA is an assembly format. It is closer to FASTA than to SAM. I think alignment to GFA needs a new format.

**Comment by richarddurbin** [comment]
This is all very interesting, and important.

The problem is, people already find GFAv2 intimidatingly complex and have therefore tended to stick with GFAv1.  Adding to the complexity will tend to make it even less attractive.  Of course the trade-off is with power of functionality.  To get people to buy into increased complexity we have to demonstrate value.  Apologies for being a bit rambling...

Richard

> On 18 Oct 2018, at 11:12, Erik Garrison <notifications@github.com> wrote:
> 
> In vg <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vgteam_vg&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=tLrRui-nzNUodb5ShCAULA&m=nbrFwsbSIK0C4p1UCgGJhQ2Cjvjt4EmfROEi7dwGyEA&s=OUWbKZE8q51HUzhOb1ATiSysjwqq5WLjvfeM9-XEp-M&e=> we use GFA for input and output. It's completely lossless with respect to the graph model, and we need only S, L, and P namespaces to represent the graph. However, there is no textual analog to SAM provided in the GFA format space. We do have cigars applied to edge overlaps and the fragment records in GFAv2. But these seem to be limited to the mapping between a read and a single sequence-containing node in the graph.
> 
> We could use Paths in GFAv1 to specify alignments, but there is no standard place to add sequences to these (which is helpful for various processing operations) or clear if an extended CIGAR can be used which we can use to reproduce the sequence of the Path using the node Sequences in the graph. Are others using Paths to represent alignments?
> 
> Alignments are useful in resequencing, when we consider the graph as a reference system. But there are other, more fundamental uses that should be considered. We can build graphs progressively with operations align and edit, that map new sequences into the graph and update the graph to include them. Tools that implement these functions can be chained together to make custom assembly pipelines. We could do this all within a coherent data model in GFA provided a SAM or PAF-like alignment schema.
> 
> Variations against a graph can also be represented as alignments, and genotypes represented as collections of these at an overlapping bubble (or other generalized site-like entity in the graph). Standard models for variants, genotypes, and bubbles would be a nice thing as well, but that's another conversation.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_GFA-2Dspec_GFA-2Dspec_issues_79&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=tLrRui-nzNUodb5ShCAULA&m=nbrFwsbSIK0C4p1UCgGJhQ2Cjvjt4EmfROEi7dwGyEA&s=85VdYFizDxm69_Frm2LeilYbz-eTNtuWrmS-ZmBOfAQ&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADRb5oO6I-5FJ5bcTTq7zvVwm1-2DRB-5Fg-2DOzks5umFQTgaJpZM4XtHH1&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=tLrRui-nzNUodb5ShCAULA&m=nbrFwsbSIK0C4p1UCgGJhQ2Cjvjt4EmfROEi7dwGyEA&s=lx4vTVEmgjWEVGD2zR7yUuwUVl147-Nxj9yMWXBpfrU&e=>.
> 




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by sjackman** [comment]
I am quite interested in aligning long reads to a GFA assembly graph. The three tools that I know of so far are `Bandage querypaths` (uses BLAST, plain text output), `spades-gmapper` (graph must be a dBG, unsure what the output format is), and `vg`.

@ekg Does using either PAF or GFA2 fragment `F` records work for your purpose?

**Comment by ggonnella** [comment]
My opinion is that GFA2 should (despite the A in the name) be considered more than an assembly format, as the extensions wrt GFA1 allow to represent different kind of sequence graphs.

I agree with @richarddurbin that adding more complexity in the specification could be a bad idea. Specifically, I think that defining new line types would not be advisable. But I would not see as critical e.g. to define and reserve new tags for specific uses for the mentioned application, for the purposes of standardization. Maybe using the available facilities, such as F lines and CIGARS, and adding ad hoc tags solves the problem. A more concrete example could help (at least me) to understand more.

**Comment by lh3** [comment]
The F-line is designed to keep the locations of reads in the assembly. Most of time, a read is placed to a single segment. In general graph alignment, in particular vg alignment, a query often walks through multiple segments, some of which are just 1bp in length. F-line or PAF is a waste of space, inconvenient to access and inefficient to process. They are not the general solution. I have little experiences with graph alignment, so I don't know what is the best solution.

Mixing graph representation and graph alignment is like merging FASTA and SAM into a single format. This can be done, but I don't think we should go for that.

**Comment by ekg** [comment]
I don't feel this has been resolved, but it is true that we haven't
discussed it in several weeks. We need a solution to this. It makes sense
to me to build it independently of GFA, but with reference to the node
identifiers as is done with reference identifiers in FASTA/SAM combinations.
