### ISSUE TITLE
GFA2: clarify in the grammar that '*' in alternations is a terminal 

### ISSUE THREAD

**Issue by kortschak** [GFA-spec/GFA-spec#80]
The text of the GFA2 grammar includes `(* | <var:int>)`, `* | [!-~]+` and `* | <trace> | <CIGAR>` along with the explanatory/confusin note expounding the meanings of a set of symbols — "* zero-or-more".

This confounds the meaning of "\*" in the alternations as a production terminal. Maybe there should be a way to mark the difference between "\*" and \*, as exists in EBNF (or maybe just use EBNF, then the need for the explanatory note goes away).

**Comment by sjackman** [comment]
Hmmm. Yes, that it is a tad confusing. The simplest fix would be an explanatory comment indicating that an asterisk `*` on its own separated by white space is the literal terminal `*`, whereas an asterisk immediately following another terminal without white space is the zero-or-more repetition operator.

I wouldn't myself be opposed to migrating to EBNF. Standards are good, and this is a standard after all. =p It would need to be proposed and pass with a vote. See `Criteria for merging a pull request ` https://github.com/GFA-spec/GFA-spec/issues/16

**Comment by kortschak** [comment]
The short term solution would be to quote literals.

**Comment by kortschak** [comment]
Yeah, if quotes are required around literals, then white space can be used to separate tokens. This is what EBNF does. A half-way with lighter-on-the-page syntax would be to use single quote only where it's needed to disambiguate a character (I don't like a single member character group, though that's an aesthetic thing that maybe I should get over).

**Comment by sjackman** [comment]
Since we're not using quotes around other literals, I feel like it would be inconsistent and confusing to use quotes around just one literal, namely `"*"`. I don't much like single member character groups either, but in this case, I think it's the least worst of the options.

**Comment by kortschak** [comment]
bot bump

**Comment by kortschak** [comment]
I may have time, but this issue going away would have made sure I would forget.

**Comment by kortschak** [comment]
Having a stale bot clear away issues that remain relevant is IMHO a bad approach to good software maintenance.

**Comment by sjackman** [comment]
We close issues that no one is actively working on. Feel free to open a PR as suggested above in https://github.com/GFA-spec/GFA-spec/issues/80#issuecomment-445564318.

**Comment by kortschak** [comment]
Yeah, I understand that, I just don't think it's a sensible approach. Closed issues lead to non-work. At the moment, I'm not able to spend the time doing this. With a closed issue, no-one else will either. Issues are for neatness, they're for keeping track of what should be done.

**Comment by sjackman** [comment]
Not all issues will eventually be addressed. Professional projects have project managers to triage and decide which issues will be addressed. In open source, unless someone volunteers their time to address the issue, the issue will not be addressed. Issues that are not important enough for anyone to volunteer to fix will not be fixed and are closed.

**Comment by kortschak** [comment]
OK. As the/a maintainer of a few open source projects I find that an odd approach, but this it your project.
