### ISSUE TITLE
Indicating that a path is circular

### ISSUE THREAD

**Issue by ekg** [GFA-spec/GFA-spec#89]
Is the preferred way of indicating if a path is circular to add:

```
Z:FL:circular
```

... to the path line?

_Originally posted by @ekg in https://github.com/GFA-spec/GFA-spec/issues/23#issuecomment-495185211_

**Comment by jmarshall** [comment]
FYI SAM has recently settled on `TP:circular` (“topology”; see samtools/hts-specs#403).

**Comment by sjackman** [comment]
Woohoo! SAM to the rescue. `TP:Z:circular` it is.
