### ISSUE TITLE
Add link attributes DI and DE to specify the estimated distance between two sequences

### ISSUE THREAD

**Issue by sjackman** [GFA-spec/GFA-spec#9]
In #8 @pb-jchin wrote…

> In reality, we only need the length of the overlap and some summary information, e.g., estimated identity.

I would like an optional field to describe an estimate of the amount of overlap/distance between two reads. I'd suggest the following:
- `DI:i` is an estimate of the distance between the end of sequence 1 and the start of sequence 2. If `DI` is negative, it is estimated that the two sequences overlap. If `DI` is positive, it is estimated that there is a gap between them. `DE:f` is the estimated error of `DI`.

Such an attribute would be useful both for estimating the amount of overlap of two sequences, as well as representing the estimated distance between two reads that is based on paired-end reads linking the two sequences. ABySS uses the `d` and `e` attributes for this purpose in its GraphViz graph.

**Comment by pmelsted** [comment]
To be a bit more specific `DE:f` would the standard deviation of the distance estimate?

**Comment by sjackman** [comment]
Yes, precisely. I should have been more specific.

**Comment by sjackman** [comment]
Superseded by #50 "Add the gap G record"
