### ISSUE TITLE
manipulating .gfa file 

### ISSUE THREAD

**Issue by dcopetti** [GFA-spec/GFA-spec#94]
Hello,
I am new in using .gfa files and I wonder how I could make a subset of a large .gfa produced by a de novo assembly (with Flye).
The file is 25 GB in size, has ~15k edges, and I would like to inspect a few thousand contigs at the time.

Is there any tool (other than command line editing) that allows to work with .gfa files?
Thanks,
Dario

**Comment by lh3** [comment]
You can extract a subgraph with [gfatools](https://github.com/lh3/gfatools):
```sh
gfatools view -l nodeId -r 10 in.gfa > out.gfa
```
or provide a list of IDs in file:
```sh
gfatools view -l @IdFile.txt -r 10 in.gfa > out.gfa
```

**Comment by dcopetti** [comment]
great, thanks!

**Comment by ekg** [comment]
@dcopetti if you want random access and manipulation, and visualization of graphs, you can use [vg](https://github.com/vgteam/vg), [odgi](https://github.com/vgteam/odgi), and [xg](https://github.com/vgteam/xg).

odgi has a python library that matches the [handle graph interface](https://github.com/vgteam/libhandlegraph).

Unlike gfatools, these tools don't consider overlap. You can use [gimbricate](https://github.com/ekg/gimbricate) and [seqwish](https://github.com/ekg/seqwish) to reduce them into a blunt-ended graph.

**Comment by ekg** [comment]
We're lacking good documentation (manpages) but there are tutorials linked from the CPANG19 course that will be helpful https://gtpb.github.io/CPANG19/, for instance https://gtpb.github.io/CPANG19/pages/toy_examples

**Comment by SwatiSaha28** [comment]
> You can extract a subgraph with [gfatools](https://github.com/lh3/gfatools):
> 
> ```shell
> gfatools view -l nodeId -r 10 in.gfa > out.gfa
> ```
> 
> or provide a list of IDs in file:
> 
> ```shell
> gfatools view -l @IdFile.txt -r 10 in.gfa > out.gfa
> ```

How can I extract those contigs that lies in a particular genomic region from a GFA file?
