### ISSUE TITLE
Implied adjacent objects in GFA2 groups are problematic

### ISSUE THREAD

**Issue by heuermh** [GFA-spec/GFA-spec#96]
https://github.com/GFA-spec/GFA-spec/blob/master/GFA2.md#group

>  An ordered collection defined in an O-line captures paths in the graph consisting of the listed objects and the implied adjacent objects between consecutive objects in the list where the orientation of the objects matters (e.g. the edge between two consecutive segments, the segment between two consecutive edges, etc.)

This implied adjacent objects is problematic to me.  I assume the use case is to include only segment id references in the O-line and infer the edges between them?  As edge `<eid:opt_id>` is optional, and more than one edge with the same `<sid1:ref> <sid2:ref>` can exist, there is no way to determine which of many possible implied adjacent objects to use.

I suggest making edge, gap, and group identifiers required fields and removing the implied adjacent objects concept from O-line; object references in an O-line should be explicit and reference identifiers.

> An unordered collection or set defined in a U-line refers to the subgraph induced by the vertices and edges in the collection (i.e. one adds all edges between a pair of segments in the list and one adds all segments adjacent to edges in the list.

Similarly, I suggest dropping the induced subgraph here, a U-line should include explicit references to every member of the set.

**Comment by heuermh** [comment]
Not cool, stale bot, you're my new least best friend.

@sjackman @ekg any chance this could be reopened for review?

**Comment by sjackman** [comment]
Allowing edge IDs to be optional was an intentional design decision. Edge identifiers are only necessary for non-strict graphs (graphs that allow parallel edges). I suspect that most assembly graphs are strict graphs (parallel edges are disallowed). Feel free to give a counterexample of a problematic ambiguous graph.
