### ISSUE TITLE
GFA2 specification does not mention optional field reserved tags

### ISSUE THREAD

**Issue by heuermh** [GFA-spec/GFA-spec#97]
Other than `VN`/version number for header and `TS`/trace point spacing for header, edge, gap, and fragment, the GFA2 specification does not mention any optional field reserved tags.  Are those defined in the GFA1 specification also reserved in GFA2?  At first glace, only `LN`/segment length would be invalid, since length `<slen:int>` is a required field of segment in GFA2.

**Comment by heuermh** [comment]
@sjackman @ekg any chance this could be reopened for review?

**Comment by ekg** [comment]
I don't have any rights in this repo.

**Comment by sjackman** [comment]
> Are those defined in the GFA1 specification also reserved in GFA2?

I believe that was the intention that any relevant optional tags in GFA1 can be used in GFA2.
