### ISSUE TITLE
making path overlap cigar list optional

### ISSUE THREAD

**Issue by ekg** [GFA-spec/GFA-spec#98]
Our GFA output now has strings of `*,*,*,*,*...` to replace the overlap cigars in the path lines.

These really serve no purpose except to inflate the files. Could we clarify in the spec that this field is simply optional, or can be replaced with a single `*`? AFAIK this is already the case for Link lines.

I can make a PR, but given that these are usually not accepted I thought I'd ask first.

If this can't be fixed here, I'm quite happy to fork the format and start making lots and lots of incompatible and incompletely documented GFAs.

**Comment by sjackman** [comment]
I agree that the whole `Overlaps` field of the path `P` record of GFA1 can be replaced by a single `*` character. Feel free to open a PR.

**Comment by ekg** [comment]
Nice!! Thank you! I will do this today.

**Comment by sjackman** [comment]
Feel free to tag me in the PR so that it doesn't get lost in my GitHub notifications.
